app/apis/urls.py
from django.urls import path
from . import welcome_page, conversation, user, privacy_policy, message
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = "api"

urlpatterns = [
    path("welcome_page/", welcome_page.WelcomePageAPI.as_view(), name="welcome_page"),
    path("conversation/", conversation.ConversationAPI.as_view(), name="conversation"),
    path("conversation/<str:name>/", conversation.ConversationAPI.as_view(), name="conversation_by_name"),
    path("user/", user.UserAPI.as_view(), name="user"),
    path(
        "privacy_policy/",
        privacy_policy.PrivacyPolicyAPI.as_view(),
        name="privacy_policy",
    ),
    path("message/", message.MessageAPI.as_view(), name="message"),
    path("auth/signin/", user.UserLoginAPI.as_view(), name="signin"),
    path("auth/signout/", user.UserLogoutAPI.as_view(), name="signout"),
    path("auth/signup/", user.UserSignupAPI.as_view(), name="signup"),
    path(
        "session/validate",
        user.SessionValidateAPI.as_view(),
        name="session_validate",
    ),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("user/profile/", user.UserProfileAPI.as_view(), name="UserProfileAPI"),
]

mrjohnnyrocha/urls.py
# backend/mrjohnnyrocha/urls.py

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

# Importing APIs
from app.apis import ForgotPasswordAPI, UserLoginAPI, UserSignupAPI, UserProfileAPI, WelcomePageAPI   

# Function for testing Sentry
def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include('rest_framework.urls', namespace='rest_framework')),
    path("api/", include('app.apis.urls', namespace='api')),  # Include app-specific URLs
    path('sentry-debug/', trigger_error),
    # Authentication and registration paths
    path("accounts/login/", UserLoginAPI.as_view(), name="login"),
    path("register/", UserSignupAPI.as_view(), name="register"),
    path("settings/", UserProfileAPI.as_view(), name="user_settings"),
    path("forgot-password/", ForgotPasswordAPI.as_view(), name="forgot_password"),
    # Password reset paths using Django's auth views
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Welcome page
    path("", WelcomePageAPI.as_view(), name="home"),
]

app/models/base.py
from django.db import models
from django.utils import timezone
import uuid


class BaseModel(models.Model):
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    name = models.CharField(max_length=100, blank=True, default="")
    created_at = models.DateTimeField(db_index=True, default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

app/models/conversation.py
from app.models.base import BaseModel
from django.db import models

class Conversation(BaseModel):
    members = models.ManyToManyField('CustomUser', related_name='conversations')
   
    def __str__(self):
        return self.name

app/models/message.py
from django.db import models
from app.models.base import BaseModel
from app.models.user import CustomUser
from app.models.conversation import Conversation

class Message(BaseModel):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.content

app/models/user.py
import uuid

from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django_countries.fields import CountryField
from django.utils.translation import gettext as _

from app.models.base import BaseModel


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_("The Email must be set"))
        user_uuid = uuid.uuid4()
        email = self.normalize_email(email)
        user = self.model(uuid=user_uuid, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))

        return self.create_user(email, password, **extra_fields)

class CustomUser(BaseModel, AbstractBaseUser, PermissionsMixin):

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name=_('groups'),
        blank=True,
        help_text=_('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
        related_name="customuser_groups",
        related_query_name="customuser",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name=_('user permissions'),
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_name="customuser_permissions",
        related_query_name="customuser",
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
    username = models.CharField(unique=True, max_length=30)
    email = models.EmailField(_('email address'), unique=True)
    country = CountryField(blank_label='(select country)')
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    profile_picture = models.ImageField(
        upload_to="profile_pics/", blank=True, null=True
    )
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

app/forms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from app.models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields 

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField()

class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'password', 'country')

class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'profile_picture', 'bio', 'phone_number', 'date_of_birth')

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign In</h1>
    <form action="{% url 'api:signin' %}" method="post">
        {% csrf_token %}
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Sign In</button>
    </form>
</body>
</html>

app/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <h1>Logout</h1>
    <p>Are you sure you want to logout?</p>
    <form action="{% url 'api:signout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <form action="{% url 'api:signup' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

app/templates/welcome_page.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome Page</title>
</head>
<body>
    <h1>Welcome to our website!</h1>
    <p>This is the welcome page.</p>
</body>
</html>